export const imageLoader = {
    "AdventureOff": require('../../../../shared/img/page/home/Adventure Off.png'),
    "Adventure": require('../../../../shared/img/page/home/Adventure.png'),
    "BackTrees": require('../../../../shared/img/page/home/Back trees.png'),
    "BattleOff": require('../../../../shared/img/page/home/Battle Off.png'),
    "Battle": require('../../../../shared/img/page/home/Battle.png'),
    "Ground": require('../../../../shared/img/page/home/Ground.png'),
    "Sky": require('../../../../shared/img/page/home/Bg.png'),
    "MarketOff": require('../../../../shared/img/page/home/Market Off.png'),
    "Market": require('../../../../shared/img/page/home/Market.png'),
    "OfficialStoreOff": require('../../../../shared/img/page/home/Official store Off.png'),
    "OfficialStore": require('../../../../shared/img/page/home/Official store.png'),
    "Stone": require('../../../../shared/img/page/home/Stone.png'),
    "TournamentOff": require('../../../../shared/img/page/home/Tournament Off.png'),
    "Tournament": require('../../../../shared/img/page/home/Tournament.png'),
    "TreesLeftSide": require('../../../../shared/img/page/home/Trees Left Side.png'),
    "TreesRightSide": require('../../../../shared/img/page/home/Trees Right Side.png'),
    "Hovering": require('../../../../shared/img/page/home/Hovering.png'),
}